apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jobttlcontroller.fullname" . }}
  labels:
    {{- include "jobttlcontroller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jobttlcontroller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jobttlcontroller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jobttlcontroller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "jobttlcontroller.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --target-ttl={{ .Values.controller.targetTTL | default 100 }}
            {{- if .Values.controller.labelSelector }}
            - --label-selector={{ .Values.controller.labelSelector }}
            {{- end }}
            - --metrics-bind-address=:{{ .Values.metrics.service.port }}
            - --health-probe-bind-address=:{{ .Values.health.port }}
            - --cert-dir=/tmp/k8s-webhook-server/serving-certs
          ports:
            - name: webhook-server
              containerPort: 9443
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.service.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.health.enabled }}
            - name: health
              containerPort: {{ .Values.health.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "jobttlcontroller.fullname" . }}-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
