apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jobttlcontroller.fullname" . }}
  labels:
    {{- include "jobttlcontroller.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jobttlcontroller.fullname" . }}
  labels:
    {{- include "jobttlcontroller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jobttlcontroller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jobttlcontroller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
