apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-with-ttl
  labels:
    ttl-controller: enabled
spec:
  template:
    spec:
      containers:
      - name: test
        image: busybox
        command: ["echo", "Hello from JobTTLController!"]
      restartPolicy: Never
  backoffLimit: 4
